### ISSUE TITLE
Proposal: Introduction to the Lambda Calculus

### ISSUE THREAD

**Issue by supersven** [lambda-pi-meetup/talks#5]
Proposal

**type**: `long talk`\
**audience**: `beginner`\
**category**: `programming language theory`

## Summary
The Lambda Calculus is the computational model behind functional programming languages and is often used in type theory.

### First Talk (09.08.2018) - Untyped Lambda Calculus
  - structure and evaluation
  - currying
  - Church encodings (Boolean, Pairs, Numerals)

### Open topics for follow-up talks
  - Simply Typed Lambda Calculus
    - Typing rules
  - Polymorphic Lambda Calculus
    - Typing rules
  - Recursion
    - Fix-Points
    - Y-Combinator

**Comment by pheymann** [comment]
Hi @supersven,
first of all, thanks for the proposal. I really appreciate that.  Regarding the number of topics, I think it would be best to break them apart and put them in multiple talks. All of them in 30min will be quite overwhelming. Do you know what would be the best way to separate them?

And another question, would your talk already available for the August meetup?

**Comment by supersven** [comment]
Hey @pheymann ,

Welcome - thanks a lot for organizing the Meetup :)

You're right, explaining all listed items in one talk would be way too much.

So, I would reduce this proposal to:
- Untyped Lambda Calculus
  - Structure and Evaluation (but without going too deep into call-by-name, call-by-value, normal forms, etc.)
  - Currying
  - Church Encodings
    - Booleans
    - Pairs
    - Numerals

In another talk we could then focus on typed lambda calculi and typing rules. If I run short of time during the talk, I could also skip one or two church encodings...

Regarding your question: Yes, I'd be glad to give this talk at the August meeting.

BTW Do you already have a location for the next meetup?

**Comment by pheymann** [comment]
Okay, I will put you on the schedule.

Regarding the location, I will book a room in XING offices (my employer).

**Comment by supersven** [comment]
Cool, thanks.

**Comment by pheymann** [comment]
One additional thing: could you send me a short bio? Just a couple of sentences (at most 5?) describing your current position and yourself a bit. Examples:

https://www.meetup.com/de-DE/Scala-Hamburg/events/251207492/

**Comment by supersven** [comment]
Hey @pheymann ,

Here you go :smile: 

```
Sven is a senior software developer at Dream IT (https://dreamit.de) where he is part of the "core architecture" team, helping to shape the technological future of one of the most successful lotto gambling platforms.

He strongly believes in Software Craftmanship practices, especially Clean Code, Pair Programming and Test Driven Development.

On his constant search for better coding approaches he got hooked by Haskell many years ago. Being interested in how things fundamentally work, he digged through some functional language compilers and read the "standard literature" about their implementation.

He loves to share his knowlegde and excitement about the underlying concepts of software development in general and functional programming in particular.

If he doesn't sit in front of a computer, you can meet him with friends in pubs or at FC St. Pauli soccer matches.
```

**Comment by supersven** [comment]
Hey,

I noticed that you polished up the talk summary and fixed a spelling mistake in my bio.

So, thank you for:
1. Organizing the MeetUp
2. Doing my homework

See you

Sven
