### ISSUE TITLE
Proposal: Theorems for Free

### ISSUE THREAD

**Issue by Fabs** [lambda-pi-meetup/talks#8]
**type**: `long talk`\
**audience**: `beginner`\
**category**: `type system`

## Summary

If the type of a polymorphic function is a theorem, every valid function implementation is a proof. In this talk, I plan to show how we can use this result in a very pragmatic way in order to guess (or even know for certain) what a function does only by looking at its type.

In this talk I intend to answer the following questions:
- How to read Haskell type notation (Hindley-Milner [0]) and how to use it to represent types in any language?
- How can we tell how many inhabitants a type has? How can that help us to guess what a function does?
- How can I apply that knowledge to common functions (id, head, fold, map)? [1]

[0] - https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system
[1] - https://www.cs.sfu.ca/CourseCentral/831/burton/Notes/July14/free.pdf

## Notes

I am still preparing the talk so I am not certain all this fits 30 minutes. But I am sure within that time I can provide some valuable information on how to reason with types, that you can bring back to your day to day.

**Comment by gpaul** [comment]
`Theorems for Free` has broad applicability. It's about being able to infer a function's definition from its signature. I wonder if we could have a few slides on how this may apply to non-functional languages like e.g., Go.

**Comment by pheymann** [comment]
Hi @Fabs ,
thanks for the proposal. That sounds really interesting.

I will take your proposal and the date we agreed on (06.09) and create a new Meetup located at Mesosphere. Could you also give me a short description of how one can reach the office (from the main entrance) and if you provide food or drinks?

**Comment by Fabs** [comment]
How to get to Mesosphere:

Mesosphere is at Am Sandtorkai 50 in Haffencity, on the 7th floor. It is a red building with an entrance in the middle. The door will be locked but we will have someone at the entrance at the start time, and a phone number you can call if you arrive later. 

Bio:
Fabs recently started a journey into the depths of Haskell after few years experimenting with Scala. He is currently a Software Engineer at Mesosphere where he works with the UI team helping the adoption of the Functional Paradigm do tame the complexity of the distributed operating system DC/OS.
